site_name:   Bio.jl
repo_url:    https://github.com/BioJulia/Bio.jl
site_description: Bioinformatics and Computational Biology Infastructure for Julia
site_author: The BioJulia Organisation 

theme: material

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
  - assets/Lapidary.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - codehilite

docs_dir: 'build'

pages:
- Home: index.md
- Manual:
  - Installation: man/install.md
  - IO API: man/reading.md
  - Sequences: man/seq.md
  - Alignments: man/alignments.md
  - Intervals: man/intervals.md
- Reference:
  - Seq: lib/seq.md
- Contributing: man/contributing.md